<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sign in_hplogo</name>
   <tag></tag>
   <elementGuidId>c8cf1918-d671-4f67-af4c-00ee35b454f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='hplogo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hplogo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3e90e093-b542-4b5d-9a1a-db5d73af64d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lnXdpd</value>
      <webElementGuid>f1bb8399-67c9-4f0e-938e-9cb1ac860d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Earth Day 2024</value>
      <webElementGuid>42d272c6-432d-4eb8-83f3-4fe9bf2cb0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>33742ffe-35f3-4ea4-96e1-aad020ec9c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/logos/doodles/2024/earth-day-2024-6753651837110453-law.gif</value>
      <webElementGuid>093e3645-c302-470e-8146-8d9b427877d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Earth Day 2024</value>
      <webElementGuid>4c44e011-fb84-4597-b457-87f2db5966ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>07974c06-a93f-4fca-aa55-ad8f739c1f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hplogo</value>
      <webElementGuid>2a110711-5af1-4090-b02e-e10f63460598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-atf</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a0617de5-71b6-4b35-a2ea-96acfb4aad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frt</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>da7d88c8-a0ac-4437-9ca1-116cba3c4354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hplogo&quot;)</value>
      <webElementGuid>6638f056-f1e6-4809-9744-c13478bc384b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='hplogo']</value>
      <webElementGuid>00f13624-711b-4dba-8126-e50a3dc5e4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Earth Day 2024']</value>
      <webElementGuid>9f701b14-994f-47d3-ba38-bbc5a035764c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>479f32c6-4f57-4ebd-af67-90cc9c2c7be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Earth Day 2024' and @src = '/logos/doodles/2024/earth-day-2024-6753651837110453-law.gif' and @title = 'Earth Day 2024' and @id = 'hplogo']</value>
      <webElementGuid>929edc51-e833-4cb9-9362-dd4391d4456e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
